#ifndef __PDK_SYSCLOCK_H__
#define __PDK_SYSCLOCK_H__

#if !defined(__PDK_IO_H__)
#  error "You must #include "pdk/io.h" instead of "pdk/sysclock.h" by itself."
#endif

//macros for clock setup

#define PDK_USE_16MHZ_IHRC_SYSCLOCK()       CLKMD = CLKMD_ENABLE_ILRC | CLKMD_ENABLE_IHRC | CLKMD_IHRC;
#define PDK_USE_8MHZ_IHRC_SYSCLOCK()        CLKMD = CLKMD_ENABLE_ILRC | CLKMD_ENABLE_IHRC | CLKMD_IHRC_DIV2;
#define PDK_USE_4MHZ_IHRC_SYSCLOCK()        CLKMD = CLKMD_ENABLE_ILRC | CLKMD_ENABLE_IHRC | CLKMD_IHRC_DIV4;
#define PDK_USE_2MHZ_IHRC_SYSCLOCK()        CLKMD = CLKMD_ENABLE_ILRC | CLKMD_ENABLE_IHRC | CLKMD_IHRC_DIV8;
#define PDK_USE_1MHZ_IHRC_SYSCLOCK()        CLKMD = CLKMD_ENABLE_ILRC | CLKMD_ENABLE_IHRC | CLKMD_IHRC_DIV16;
#define PDK_USE_500KHZ_IHRC_SYSCLOCK()      CLKMD = CLKMD_ENABLE_ILRC | CLKMD_ENABLE_IHRC | CLKMD_IHRC_DIV32;
#define PDK_USE_250KHZ_IHRC_SYSCLOCK()      CLKMD = CLKMD_ENABLE_ILRC | CLKMD_ENABLE_IHRC | CLKMD_IHRC_DIV64;

#define PDK_USE_ILRC_SYSCLOCK()             CLKMD = CLKMD_ENABLE_ILRC | CLKMD_ENABLE_IHRC | CLKMD_ILRC;
#define PDK_USE_ILRC_DIV4_SYSCLOCK()        CLKMD = CLKMD_ENABLE_ILRC | CLKMD_ENABLE_IHRC | CLKMD_ILRC_DIV4;
#define PDK_USE_ILRC_DIV16_SYSCLOCK()       CLKMD = CLKMD_ENABLE_ILRC | CLKMD_ENABLE_IHRC | CLKMD_ILRC_DIV16;

#endif //__PDK_SYSCLOCK_H__
